current:
  default: 0
  description:
    en: "Current Donation"
goal:
  default: 150
  description:
    en: "Donation Goal"
goal_title:
  default: Goal
  description:
    en: "Goal title"
left_symbol:
  default: $
  description:
    en: "Currency left side symbol. Remove this if you use right side symbol currency."
right_symbol:
  default: ""
  description:
    en: "Currency right side symbol. Remove this if you use left side symbol currency."
period:
  default: month
  description:
    en: "Donation Period time. e.g. month"
